In [1]:
# importing necessary libraries.
import pandas as pd
import numpy as np
import os

In [2]:
os.getcwd()

'C:\\Users\\Rahul\\Desktop\\DATA SCIENCE\\DataSets\\Self\\Projects\\4.SentimentAnalysis'

# Loading Data.

In [3]:
text=pd.read_csv('Tweets.csv')

In [4]:
text

tweet_id airline_sentiment  airline_sentiment_confidence  \
0      570306133677760513           neutral                        1.0000   
1      570301130888122368          positive                        0.3486   
2      570301083672813571           neutral                        0.6837   
3      570301031407624196          negative                        1.0000   
4      570300817074462722          negative                        1.0000   
...                   ...               ...                           ...   
14635  569587686496825344          positive                        0.3487   
14636  569587371693355008          negative                        1.0000   
14637  569587242672398336           neutral                        1.0000   
14638  569587188687634433          negative                        1.0000   
14639  569587140490866689           neutral                        0.6771   

               negativereason  negativereason_confidence         airline  \
0                         NaN                        NaN  Virgin America   
1                         NaN                     0.0000  Virgin America   
2                         NaN                        NaN  Virgin America   
3                  Bad Flight                     0.7033  Virgin America   
4                  Can't Tell                     1.0000  Virgin America   
...                       ...                        ...             ...   
14635                     NaN                     0.0000        American   
14636  Customer Service Issue                     1.0000        American   
14637                     NaN                        NaN        American   
14638  Customer Service Issue                     0.6659        American   
14639                     NaN                     0.0000        American   

      airline_sentiment_gold             name negativereason_gold  \
0                        NaN          cairdin                 NaN   
1                        NaN         jnardino                 NaN   
2                        NaN       yvonnalynn                 NaN   
3                        NaN         jnardino                 NaN   
4                        NaN         jnardino                 NaN   
...                      ...              ...                 ...   
14635                    NaN  KristenReenders                 NaN   
14636                    NaN         itsropes                 NaN   
14637                    NaN         sanyabun                 NaN   
14638                    NaN       SraJackson                 NaN   
14639                    NaN        daviddtwu                 NaN   

       retweet_count                                               text  \
0                  0                @VirginAmerica What @dhepburn said.   
1                  0  @VirginAmerica plus you've added commercials t...   
2                  0  @VirginAmerica I didn't today... Must mean I n...   
3                  0  @VirginAmerica it's really aggressive to blast...   
4                  0  @VirginAmerica and it's a really big bad thing...   
...              ...                                                ...   
14635              0  @AmericanAir thank you we got on a different f...   
14636              0  @AmericanAir leaving over 20 minutes Late Flig...   
14637              0  @AmericanAir Please bring American Airlines to...   
14638              0  @AmericanAir you have my money, you change my ...   
14639              0  @AmericanAir we have 8 ppl so we need 2 know h...   

      tweet_coord              tweet_created tweet_location  \
0             NaN  2015-02-24 11:35:52 -0800            NaN   
1             NaN  2015-02-24 11:15:59 -0800            NaN   
2             NaN  2015-02-24 11:15:48 -0800      Lets Play   
3             NaN  2015-02-24 11:15:36 -0800            NaN   
4             NaN  2015-02-24 11:14:45 -0800            NaN   
...           ...                        ...            ...   
14635   

In [5]:
# There are 14640 rows and 15 columns.

# DataUnderstanding.

In [6]:
text.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 15 columns):
tweet_id                        14640 non-null int64
airline_sentiment               14640 non-null object
airline_sentiment_confidence    14640 non-null float64
negativereason                  9178 non-null object
negativereason_confidence       10522 non-null float64
airline                         14640 non-null object
airline_sentiment_gold          40 non-null object
name                            14640 non-null object
negativereason_gold             32 non-null object
retweet_count                   14640 non-null int64
text                            14640 non-null object
tweet_coord                     1019 non-null object
tweet_created                   14640 non-null object
tweet_location                  9907 non-null object
user_timezone                   9820 non-null object
dtypes: float64(2), int64(2), object(11)
memory usage: 1.7+ MB


In [7]:
# finding all the unique values present in the 'negativereason' column.
text['negativereason'].value_counts()

Customer Service Issue         2910
Late Flight                    1665
Can't Tell                     1190
Cancelled Flight                847
Lost Luggage                    724
Bad Flight                      580
Flight Booking Problems         529
Flight Attendant Complaints     481
longlines                       178
Damaged Luggage                  74
Name: negativereason, dtype: int64

In [8]:
# finding all the unique values present in the 'airline_sentiment' column.
text['airline_sentiment'].value_counts()

negative    9178
neutral     3099
positive    2363
Name: airline_sentiment, dtype: int64

In [9]:
# finding all the unique values present in the 'negativereason_gold' column.
text['negativereason_gold'].value_counts()

Customer Service Issue                      12
Late Flight                                  4
Can't Tell                                   3
Cancelled Flight                             3
Cancelled Flight\nCustomer Service Issue     2
Flight Attendant Complaints                  1
Late Flight\nFlight Attendant Complaints     1
Customer Service Issue\nLost Luggage         1
Late Flight\nLost Luggage                    1
Late Flight\nCancelled Flight                1
Lost Luggage\nDamaged Luggage                1
Customer Service Issue\nCan't Tell           1
Bad Flight                                   1
Name: negativereason_gold, dtype: int64

In [10]:
# finding all the unique values present in the 'airline' column.
text['airline'].value_counts()

United            3822
US Airways        2913
American          2759
Southwest         2420
Delta             2222
Virgin America     504
Name: airline, dtype: int64

In [11]:
text.isnull().sum()

tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5462
negativereason_confidence        4118
airline                             0
airline_sentiment_gold          14600
name                                0
negativereason_gold             14608
retweet_count                       0
text                                0
tweet_coord                     13621
tweet_created                       0
tweet_location                   4733
user_timezone                    4820
dtype: int64

### Dropping columns with more than 50 percent null values.

In [12]:
text.drop(['name','tweet_id', 'negativereason','negativereason_confidence','airline_sentiment_gold',
           'negativereason_gold','tweet_coord','tweet_location','airline_sentiment_confidence',
           'retweet_count','tweet_created','airline','user_timezone'], axis = 1,inplace=True) 

In [13]:
text.head()

airline_sentiment                                               text
0           neutral                @VirginAmerica What @dhepburn said.
1          positive  @VirginAmerica plus you've added commercials t...
2           neutral  @VirginAmerica I didn't today... Must mean I n...
3          negative  @VirginAmerica it's really aggressive to blast...
4          negative  @VirginAmerica and it's a really big bad thing...

In [14]:
text.shape

(14640, 2)

# Text Cleaning.

In [15]:
import nlp_utils

In [16]:
clean_text= text['text'].apply(nlp_utils.lemmatization_sentence)

In [17]:
clean_text.head()

0                      virginamerica what dhepburn say
1    virginamerica plus you have add commercial to ...
2    virginamerica i do not today ... must mean i n...
3    virginamerica it be really aggressive to blast...
4    virginamerica and it be a really big bad thing...
Name: text, dtype: object

# 1. Tokenization.

In [18]:
import nltk.corpus

In [19]:
corpus=clean_text

In [20]:
def clean_nda(corpus):
    tokens = nlp_utils.w_tokenization(corpus)

In [21]:
corpus

0                          virginamerica what dhepburn say
1        virginamerica plus you have add commercial to ...
2        virginamerica i do not today ... must mean i n...
3        virginamerica it be really aggressive to blast...
4        virginamerica and it be a really big bad thing...
                               ...                        
14635    americanair thank you we get on a different fl...
14636    americanair leave over 20 minute late flight n...
14637    americanair please bring american airline to b...
14638    americanair you have my money you change my fl...
14639    americanair we have 8 ppl so we need 2 know ho...
Name: text, Length: 14640, dtype: object

# 2. Removing Special Characters.

In [22]:
import re

In [23]:
def clean_special(corpus):

    return re.sub(r'[^a-z0-9 ]','',corpus)

In [24]:
corpus = corpus.apply(clean_special)

In [25]:
corpus

0                          virginamerica what dhepburn say
1        virginamerica plus you have add commercial to ...
2        virginamerica i do not today  must mean i need...
3        virginamerica it be really aggressive to blast...
4        virginamerica and it be a really big bad thing...
                               ...                        
14635    americanair thank you we get on a different fl...
14636    americanair leave over 20 minute late flight n...
14637    americanair please bring american airline to b...
14638    americanair you have my money you change my fl...
14639    americanair we have 8 ppl so we need 2 know ho...
Name: text, Length: 14640, dtype: object

# 2a.Removing numeric, alphanumeric, decimals.

In [26]:
def num_dec_al(word):
    if word.isnumeric():
        return 'xxxxxx'
    elif word.isdecimal():
        return 'xxx...'
    elif word.isalpha():
        return word
    else:
        return 'xxxaaa'

In [27]:
def clean_nda(corpus):
    tokens = nlp_utils.w_tokenization(corpus)
    map_list = list(map(num_dec_al,tokens))
    return " ".join(map_list)

In [28]:
corpus_nda = list(map(clean_nda,corpus))

In [29]:
corpus_nda

['virginamerica what dhepburn say',
 'virginamerica plus you have add commercial to the experience tacky',
 'virginamerica i do not today must mean i need to take another trip',
 'virginamerica it be really aggressive to blast obnoxious entertainment in your guest face amp they have little recourse',
 'virginamerica and it be a really big bad thing about it',
 'virginamerica seriously would pay xxxxxx a flight for seat that do not have this playing it be really the only bad thing about fly va',
 'virginamerica yes nearly every time i fly vx this ear worm win t go away',
 'virginamerica really miss a prime opportunity for men without hat parody there https xxxaaa',
 'virginamerica well i do notbut now i do d',
 'virginamerica it be amaze and arrive an hour early you be too good to me',
 'virginamerica do you know that suicide be the second leading cause of death among teen xxxxxx',
 'virginamerica i lt xxxxxx pretty graphic so much good than minimal iconography d',
 'virginamerica this 

# 3. Expanding Contractions and converting to lower case.

In [30]:
import contractions

In [31]:
conm = contractions.CONTRACTION_MAP
def contraction_remove(corpus_nda):
    for key,value in conm.items():
        corpus_nda = re.sub(r"{}".format(key),'{}'.format(value),corpus_nda)
        
    return corpus_nda

In [32]:
import string
special = string.punctuation
def w_tokenization(corpus_nda):
    # convert into lower case
    corpus_nda = corpus_nda.lower()
    # contraction
    corpus_nda = contraction_remove(corpus_nda)
    # 
    tokens = nltk.word_tokenize(corpus_nda) # word tokens
    # step-1: compare
    without_special = []
    for word in tokens:
        if word not in special:
            without_special.append(word)

    return without_special

In [33]:
corpus_nda

['virginamerica what dhepburn say',
 'virginamerica plus you have add commercial to the experience tacky',
 'virginamerica i do not today must mean i need to take another trip',
 'virginamerica it be really aggressive to blast obnoxious entertainment in your guest face amp they have little recourse',
 'virginamerica and it be a really big bad thing about it',
 'virginamerica seriously would pay xxxxxx a flight for seat that do not have this playing it be really the only bad thing about fly va',
 'virginamerica yes nearly every time i fly vx this ear worm win t go away',
 'virginamerica really miss a prime opportunity for men without hat parody there https xxxaaa',
 'virginamerica well i do notbut now i do d',
 'virginamerica it be amaze and arrive an hour early you be too good to me',
 'virginamerica do you know that suicide be the second leading cause of death among teen xxxxxx',
 'virginamerica i lt xxxxxx pretty graphic so much good than minimal iconography d',
 'virginamerica this 

# 4.Removing Stopwords and Stemming, Lemmatization.

In [34]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, LancasterStemmer, SnowballStemmer
from nltk.stem import WordNetLemmatizer

In [35]:
def stemming(corpus_nda):
    tokens = w_tokenization(corpus_nda)
    stem_words = []
    for w in tokens:
        stem_words.append(snow.stem(w))

    return " ".join(stem_words)

In [36]:
lemma = WordNetLemmatizer() # initilizing word net
def lemmatization_sentence(corpus_nda,stopwords,stop=True):
    # computing parts of speech
    tokens = w_tokenization(corpus_nda)
    tag_list = pos_tag(tokens,tagset=None)
    lema_sent =[] # initizaing empty list

    for token,pos_token in tag_list:
        #if token not in stopwords:

        if pos_token.startswith('V'): # verb
            pos_val = 'v'
        elif pos_token.startswith('J'): # adjective
            pos_val = 'a'
        elif pos_token.startswith('R'): # adverb
            pos_val = 'r'
        else:# any parts of speech except verb, adjective, adverb
            pos_val = 'n'

        lema_token = lemma.lemmatize(token,pos_val) # computing lematization
        lema_sent.append(lema_token) # append values in list
    return " ".join(lema_sent)

# Word Embedding using CountVectorizer.

In [37]:
# bag of words
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [38]:
cv1 = CountVectorizer(max_features=2000) # bag of words

In [39]:
bow = cv1.fit_transform(clean_text)

In [40]:
X = bow.toarray()

In [41]:
X.shape

(14640, 2000)

In [42]:
col = cv1.get_feature_names()

In [43]:
df_x = pd.DataFrame(X,columns=col)

In [44]:
y = text['airline_sentiment'].replace(['neutral','positive','negative'],[0,1,2]).values

In [45]:
y

array([0, 1, 0, ..., 0, 2, 0], dtype=int64)

In [46]:
df_x.head()

00  000  03  10  100  1000  10pm  11  12  13  ...  young  your  youre  \
0   0    0   0   0    0     0     0   0   0   0  ...      0     0      0   
1   0    0   0   0    0     0     0   0   0   0  ...      0     0      0   
2   0    0   0   0    0     0     0   0   0   0  ...      0     0      0   
3   0    0   0   0    0     0     0   0   0   0  ...      0     1      0   
4   0    0   0   0    0     0     0   0   0   0  ...      0     0      0   

   yours  yr  yup  yvr  yyz  zero  zone  
0      0   0    0    0    0     0     0  
1      0   0    0    0    0     0     0  
2      0   0    0    0    0     0     0  
3      0   0    0    0    0     0     0  
4      0   0    0    0    0     0     0  

[5 rows x 2000 columns]

In [47]:
corpus_nda[1]

'virginamerica plus you have add commercial to the experience tacky'

# Word Embedding using TF-IDF.

In [48]:
tfidf = TfidfVectorizer(max_features=3000)

In [49]:
tf_vector = tfidf.fit_transform(corpus_nda)

In [50]:
x_tfidf = tf_vector.toarray()

In [51]:
df_x_tfidf = pd.DataFrame(x_tfidf,columns=tfidf.get_feature_names())
df_x_tfidf.head(1)

aa  aadvantage  abandon  abc  ability  able  aboard  about  above  abq  \
0  0.0         0.0      0.0  0.0      0.0   0.0     0.0    0.0    0.0  0.0   

   ...  yourselves  yousuck   yr  yuma  yup  yvr  yyz  zero  zone  zurich  
0  ...         0.0      0.0  0.0   0.0  0.0  0.0  0.0   0.0   0.0     0.0  

[1 rows x 3000 columns]

# Splitting Dataset.

In [52]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_tfidf,y,test_size=0.33, random_state=42)

In [53]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((9808, 3000), (4832, 3000), (9808,), (4832,))

#                             Using Machine Learning Models.

## NaiveBayes

In [54]:
from sklearn.naive_bayes import MultinomialNB

In [55]:
model = MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [56]:
y_pred = model.predict(x_test)

In [57]:
from sklearn import metrics

In [58]:
cr = metrics.classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.76      0.27      0.40       984
           1       0.91      0.35      0.51       763
           2       0.73      0.99      0.84      3085

    accuracy                           0.74      4832
   macro avg       0.80      0.54      0.58      4832
weighted avg       0.76      0.74      0.70      4832



In [59]:
y = text['airline_sentiment'].value_counts(normalize=True)

In [60]:
metrics.cohen_kappa_score(y_test,y_pred)

0.3867734775657853

# Logistic Regression.

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, auc, confusion_matrix, roc_auc_score, roc_curve, recall_score

In [62]:
#fit the model on train data 
log_reg = LogisticRegression().fit(x_train,y_train)

#predict on train 
train_preds = log_reg.predict(x_train)
#accuracy on train
print("Model accuracy on train is: ", accuracy_score(y_train, train_preds))

#predict on test
test_preds = log_reg.predict(x_test)
#accuracy on test
print("Model accuracy on test is: ", accuracy_score(y_test, test_preds))
print('-'*50)

#We got good accuracy which means our model is performing quite well 
#ROC 
#print("ROC score on train is: ", roc_auc_score(y_train, train_preds))
#print("ROC score on test is: ", roc_auc_score(y_test, test_preds))
#print('-'*50)

#Confusion matrix
print("confusion_matrix train is: ", confusion_matrix(y_train, train_preds))
print("confusion_matrix test is: ", confusion_matrix(y_test, test_preds))
print('Wrong predictions out of total')
print('-'*50)

# Wrong Predictions made.
print((y_test !=test_preds).sum(),'/',((y_test == test_preds).sum()+(y_test != test_preds).sum()))

Model accuracy on train is:  0.8613376835236541
Model accuracy on test is:  0.8060844370860927
--------------------------------------------------
confusion_matrix train is:  [[1419  103  593]
 [ 146 1160  294]
 [ 171   53 5869]]
confusion_matrix test is:  [[ 538   54  392]
 [ 109  466  188]
 [ 147   47 2891]]
Wrong predictions out of total
--------------------------------------------------
937 / 4832


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [63]:
metrics.cohen_kappa_score(y_test,test_preds)

0.6037566758431796

# DecisionTree

In [64]:
from sklearn.tree import DecisionTreeClassifier

In [65]:
#fit the model on train data 
DT = DecisionTreeClassifier().fit(x_train,y_train)

#predict on train 
train_preds3 = DT.predict(x_train)
#accuracy on train
print("Model accuracy on train is: ", accuracy_score(y_train, train_preds3))

#predict on test
test_preds3 = DT.predict(x_test)
#accuracy on test
print("Model accuracy on test is: ", accuracy_score(y_test, test_preds3))
print('-'*50)

#Confusion matrix
print("confusion_matrix train is: ", confusion_matrix(y_train, train_preds3))
print("confusion_matrix test is: ", confusion_matrix(y_test, test_preds3))
print('Wrong predictions out of total')
print('-'*50)

# Wrong Predictions made.
print((y_test !=test_preds3).sum(),'/',((y_test == test_preds3).sum()+(y_test != test_preds3).sum()))


Model accuracy on train is:  0.9966353996737357
Model accuracy on test is:  0.6941225165562914
--------------------------------------------------
confusion_matrix train is:  [[2102   12    1]
 [  10 1589    1]
 [   8    1 6084]]
confusion_matrix test is:  [[ 463  132  389]
 [ 137  410  216]
 [ 410  194 2481]]
Wrong predictions out of total
--------------------------------------------------
1478 / 4832


In [66]:
metrics.cohen_kappa_score(y_test,test_preds3)

0.41807353771104283

# RandomForestClassifier.

In [67]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
#fit the model on train data 
RF=RandomForestClassifier().fit(x_train,y_train)
#predict on train 
train_preds4 = RF.predict(x_train)
#accuracy on train
print("Model accuracy on train is: ", accuracy_score(y_train, train_preds4))

#predict on test
test_preds4 = RF.predict(x_test)
#accuracy on test
print("Model accuracy on test is: ", accuracy_score(y_test, test_preds4))
print('-'*50)

#Confusion matrix
print("confusion_matrix train is: ", confusion_matrix(y_train, train_preds4))
print("confusion_matrix test is: ", confusion_matrix(y_test, test_preds4))
print('Wrong predictions out of total')
print('-'*50)

# Wrong Predictions made.
print((y_test !=test_preds4).sum(),'/',((y_test == test_preds4).sum()+(y_test != test_preds4).sum()))


Model accuracy on train is:  0.9966353996737357
Model accuracy on test is:  0.7706953642384106
--------------------------------------------------
confusion_matrix train is:  [[2095   14    6]
 [   8 1591    1]
 [   3    1 6089]]
confusion_matrix test is:  [[ 391   46  547]
 [  91  351  321]
 [  85   18 2982]]
Wrong predictions out of total
--------------------------------------------------
1108 / 4832


In [69]:
metrics.cohen_kappa_score(y_test,test_preds4)

0.4947476978268376

# K-Nearest Neighbours.

In [70]:
from sklearn.neighbors import KNeighborsClassifier

In [71]:
#fit the model on train data 
KNN = KNeighborsClassifier().fit(x_train,y_train)
#predict on train 
train_preds5 = KNN.predict(x_train)
#accuracy on train
print("Model accuracy on train is: ", accuracy_score(y_train, train_preds5))

#predict on test
test_preds5 = KNN.predict(x_test)
#accuracy on test
print("Model accuracy on test is: ", accuracy_score(y_test, test_preds5))
print('-'*50)

#Confusion matrix
print("confusion_matrix train is: ", confusion_matrix(y_train, train_preds5))
print("confusion_matrix test is: ", confusion_matrix(y_test, test_preds5))
print('Wrong predictions out of total')
print('-'*50)

# Wrong Predictions made.
print((y_test !=test_preds5).sum(),'/',((y_test == test_preds5).sum()+(y_test != test_preds5).sum()))


Model accuracy on train is:  0.8067903752039152
Model accuracy on test is:  0.7177152317880795
--------------------------------------------------
confusion_matrix train is:  [[1518  172  425]
 [ 300 1119  181]
 [ 588  229 5276]]
confusion_matrix test is:  [[ 540  121  323]
 [ 157  467  139]
 [ 464  160 2461]]
Wrong predictions out of total
--------------------------------------------------
1364 / 4832


In [72]:
metrics.cohen_kappa_score(y_test,test_preds5)

0.4776473314581251

# SupportVectorMachine.

In [73]:
from sklearn.svm import SVC

In [74]:
#fit the model on train data 
SVM = SVC(kernel='linear')
SVM.fit(x_train, y_train)

#predict on train 
train_preds6 = SVM.predict(x_train)
#accuracy on train
print("Model accuracy on train is: ", accuracy_score(y_train, train_preds6))

#predict on test
test_preds6 = SVM.predict(x_test)
#accuracy on test
print("Model accuracy on test is: ", accuracy_score(y_test, test_preds6))
print('-'*50)

#Confusion matrix
print("confusion_matrix train is: ", confusion_matrix(y_train, train_preds6))
print("confusion_matrix test is: ", confusion_matrix(y_test, test_preds6))
print('Wrong predictions out of total')
print('-'*50)

#print("recall", metrics.recall_score(y_test, test_preds6))
#print('-'*50)

# Wrong Predictions made.
print((y_test !=test_preds6).sum(),'/',((y_test == test_preds6).sum()+(y_test != test_preds6).sum()))


Model accuracy on train is:  0.8751019575856444
Model accuracy on test is:  0.8050496688741722
--------------------------------------------------
confusion_matrix train is:  [[1489  102  524]
 [ 144 1235  221]
 [ 181   53 5859]]
confusion_matrix test is:  [[ 567   61  356]
 [ 115  489  159]
 [ 188   63 2834]]
Wrong predictions out of total
--------------------------------------------------
942 / 4832


In [75]:
metrics.cohen_kappa_score(y_test,test_preds6)

0.6107211642075951

In [76]:
# Hence Support Vector Machines gives a better accuracy as compared to other models, giving us 942/4832 wrong predictions.
# Next better model is Logistic Regression with 937/4832 wrong predictions.
# Further, HyperParamterTuning can be done on SVM in order to select right parameters and improve the overall accuracy.